In [ ]:
# -*- coding: utf-8
# Repórter Brasil (https://ruralometro2022.reporterbrasil.org.br/)
# Reinaldo Chaves (@paidatocandeira)
# Lista os IDs dos doadores de deputados inscritos nas listas de irregularidades do projeto, eliminando 
# repetições
# Lista as empresas dos doadores, a partir dos IDs
# Verifica se as empresas estão nas listas de irregularidades

In [1]:
import pandas as pd
from datetime import datetime
import unidecode

In [2]:
def f(str):
    try:
        return (unidecode.unidecode(str))
    except:
        return (str)

In [3]:
# Doações diretas vindas de inscritos com embargos no Ibama

In [29]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_1 = pd.read_csv("resultados/embargos_ibama/doacoes_vindas_pessoas_com_embargos_ibama_2018.csv", **kwargs)

In [30]:
doacoes_1.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_nome', 'doacoes_tipo',
       'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [31]:
doacoes_1_dep = doacoes_1[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [32]:
doacoes_1 = doacoes_1[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [7]:
# Doações indiretas vindas de inscritos com embargos no Ibama

In [33]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_2 = pd.read_csv("resultados/embargos_ibama/doacoes_indiretas_vindas_pessoas_com_embargos_ibama_2018.csv", **kwargs)

In [34]:
doacoes_2.columns

Index(['valor', 'politico_id', 'politico_id.1', 'entidade_id', 'entidade_nome',
       'sequencialdoador_id', 'doacoes_tipo', 'origem_do_dinheiro_no_tse',
       'data'],
      dtype='object')

In [35]:
doacoes_2_dep = doacoes_2[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [36]:
doacoes_2 = doacoes_2[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [11]:
# Doações originárias vindas de inscritos com embargos no Ibama

In [37]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_3 = pd.read_csv("resultados/embargos_ibama/doacoes_originarias_vindas_pessoas_com_embargos_ibama_2018.csv", **kwargs)

In [38]:
doacoes_3.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_nome', 'doacoes_tipo',
       'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [39]:
doacoes_3_dep = doacoes_3[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [40]:
doacoes_3 = doacoes_3[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [15]:
# Doações diretas vindas de inscritos com autos de infração no Ibama

In [41]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_4 = pd.read_csv("resultados/autos_ibama/doacoes_diretas_vindas_pessoas_com_autos_de_infracao_ibama_2018.csv", **kwargs)

In [42]:
doacoes_4.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_id_mascarada',
       'entidade_nome', 'doacoes_tipo', 'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [43]:
doacoes_4_dep = doacoes_4[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [44]:
doacoes_4 = doacoes_4[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [19]:
# Doações indiretas vindas de inscritos com autos de infração no Ibama

In [45]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_5 = pd.read_csv("resultados/autos_ibama/doacoes_indiretas_vindas_pessoas_com_autos_de_infracao_ibama_2018.csv", **kwargs)

In [46]:
doacoes_5.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_id_mascarada',
       'entidade_nome', 'sequencialdoador_id', 'doacoes_tipo',
       'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [47]:
doacoes_5_dep = doacoes_5[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [48]:
doacoes_5 = doacoes_5[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [23]:
# Doações originárias vindas de inscritos com autos no Ibama

In [49]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_6 = pd.read_csv("resultados/autos_ibama/doacoes_originarias_vindas_pessoas_com_autos_ibama_2018.csv", **kwargs)

In [50]:
doacoes_6.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_id_mascarada',
       'entidade_nome', 'doacoes_tipo', 'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [51]:
doacoes_6_dep = doacoes_6[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [52]:
doacoes_6 = doacoes_6[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [27]:
# Doações diretas vindas de inscritos com autos de infração no ICMBIO

In [53]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_7 = pd.read_csv("resultados/autos_icmbio/doacoes_vindas_pessoas_com_autos_icmbio_2018.csv", **kwargs)

In [54]:
doacoes_7.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_nome', 'doacoes_tipo',
       'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [55]:
doacoes_7_dep = doacoes_7[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [56]:
doacoes_7 = doacoes_7[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [31]:
# Doações diretas vindas de inscritos com autos de infração trabalhistas

In [57]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_8 = pd.read_csv("resultados/autos_mte/doacoes_diretas_vindas_pessoas_com_autos_de_mte_2018.csv", **kwargs)

In [58]:
doacoes_8.columns

Index(['valor', 'politico_id', 'entidade_id', 'entidade_nome', 'doacoes_tipo',
       'origem_do_dinheiro_no_tse', 'data'],
      dtype='object')

In [59]:
doacoes_8_dep = doacoes_8[['entidade_id', 'entidade_nome', 'doacoes_tipo', 'politico_id']]

In [60]:
doacoes_8.shape

(138, 7)

In [61]:
doacoes_8 = doacoes_8[['entidade_id', 'entidade_nome', 'doacoes_tipo']]

In [36]:
frames = [doacoes_1, doacoes_2, doacoes_3, doacoes_4, doacoes_5, doacoes_6, doacoes_7, doacoes_8] 
todas_doacoes = pd.concat(frames)
todas_doacoes['cpf_mascarado']= '***'+todas_doacoes['entidade_id'].str[3:9]+'**'

todas_doacoes["entidade_nome"] = todas_doacoes["entidade_nome"].str.upper()
todas_doacoes["entidade_nome"] = todas_doacoes["entidade_nome"].apply(f)

todas_doacoes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 587 entries, 0 to 137
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   entidade_id    587 non-null    object
 1   entidade_nome  587 non-null    object
 2   doacoes_tipo   587 non-null    object
 3   cpf_mascarado  587 non-null    object
dtypes: object(4)
memory usage: 22.9+ KB

In [62]:
frames = [doacoes_1_dep, doacoes_2_dep, doacoes_3_dep, doacoes_4_dep, doacoes_5_dep, doacoes_6_dep, doacoes_7_dep, doacoes_8_dep] 
todas_doacoes_dep = pd.concat(frames)
todas_doacoes_dep['cpf_mascarado']= '***'+todas_doacoes_dep['entidade_id'].str[3:9]+'**'

todas_doacoes_dep["entidade_nome"] = todas_doacoes_dep["entidade_nome"].str.upper()
todas_doacoes_dep["entidade_nome"] = todas_doacoes_dep["entidade_nome"].apply(f)

todas_doacoes_dep.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 587 entries, 0 to 137
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   entidade_id    587 non-null    object
 1   entidade_nome  587 non-null    object
 2   doacoes_tipo   587 non-null    object
 3   politico_id    587 non-null    object
 4   cpf_mascarado  587 non-null    object
dtypes: object(5)
memory usage: 27.5+ KB

In [63]:
todas_doacoes_dep.head()

,entidade_id,entidade_nome,doacoes_tipo,politico_id,cpf_mascarado
0,50913735272,ANAILTON FRANCA PINHEIRO,direta,65595564253,***137352**
1,43334490220,JOSE RONALDO DE MATOS DIAS,direta,32770553291,***344902**
2,18609287734,LUCIANO MAFFRA DE VASCONCELLOS,direta,79753566549,***092877**
3,18609287734,LUCIANO MAFFRA DE VASCONCELLOS,direta,79753566549,***092877**
4,34814396600,LUTZ VIANA RODRIGUES JUNIOR,direta,38247186500,***143966**

In [64]:
todas_doacoes_dep.to_excel('D://Code//RB//repo//rura2//resultados//downloads_site//todas_doacoes_com_cpfs_deputados.xlsx',sheet_name='Sheet1',index=False)

In [37]:
todas_doacoes = todas_doacoes.drop_duplicates(['cpf_mascarado', 'entidade_nome'], keep='first')
todas_doacoes.shape

(182, 4)

In [38]:
empresas_encontradas = todas_doacoes[(todas_doacoes['cpf_mascarado'] == '***836606**') &
                              (todas_doacoes['entidade_nome'] == 'RUBENS MENIN TEIXEIRA DE SOUZA')]
empresas_encontradas

Empty DataFrame
Columns: [entidade_id, entidade_nome, doacoes_tipo, cpf_mascarado]
Index: []

### Empresas de doadores

In [39]:
TextFileReader = pd.read_csv('D://Code//nova_receita//socios_fev_2022.csv',\
                             chunksize=1000,\
                             sep=',',\
                             converters={'cnpj': lambda x: str(x),
                                         'cnpj_basico': lambda x: str(x)
                                        },\
                             usecols=['cnpj', 
                                      'cnpj_basico', 
                                      'identificador_de_socio', 
                                      'nome_socio', 
                                      'cnpj_cpf_socio', 
                                      'qualificacao_socio', 
                                      'pais',
                                      'representante_legal', 
                                      'nome_representante'])

In [40]:
now = datetime.now()
print("A extração começou às: ", now)

conta = 0
for df in TextFileReader:
    
    df["nome_socio"] = df["nome_socio"].str.upper()
    df["nome_socio"] = df["nome_socio"].apply(f)

    empresas_encontradas = pd.merge(todas_doacoes, \
                                 df, \
                                 left_on= ['cpf_mascarado', 'entidade_nome'],\
                                 right_on=['cnpj_cpf_socio', 'nome_socio'])
    
    if empresas_encontradas.empty is False:
        if conta == 0:
            df_socio1 = empresas_encontradas.copy()
        else:
            df_socio1 = pd.concat([df_socio1, empresas_encontradas])             
    
        conta = conta + 1
        
now = datetime.now()
print("A extração terminou às: ", now)

A extração começou às:  2022-08-10 10:01:22.819320
A extração terminou às:  2022-08-10 10:03:51.511701

In [55]:
df_socio1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1465 entries, 0 to 0
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   entidade_id             1465 non-null   object
 1   entidade_nome           1465 non-null   object
 2   doacoes_tipo            1465 non-null   object
 3   cpf_mascarado           1465 non-null   object
 4   cnpj                    1465 non-null   object
 5   cnpj_basico             1465 non-null   object
 6   identificador_de_socio  1465 non-null   int64
 7   nome_socio              1465 non-null   object
 8   cnpj_cpf_socio          1465 non-null   object
 9   qualificacao_socio      1465 non-null   int64
 10  pais                    0 non-null      float64
 11  representante_legal     1465 non-null   object
 12  nome_representante      1 non-null      object
dtypes: float64(1), int64(2), object(10)
memory usage: 160.2+ KB

In [56]:
df_socio1

,entidade_id,entidade_nome,doacoes_tipo,cpf_mascarado,cnpj,cnpj_basico,identificador_de_socio,nome_socio,cnpj_cpf_socio,qualificacao_socio,pais,representante_legal,nome_representante
0,00279046871,SANDRO DA MABEL ANTONIO SCODRO,direta,***790468**,32329476000167,32329476,2,SANDRO DA MABEL ANTONIO SCODRO,***790468**,49,NaN,***000000**,NaN
0,92588298834,MARIO MAURICIO VASQUEZ BELTRAO,direta,***882988**,05296337000101,05296337,2,MARIO MAURICIO VASQUEZ BELTRAO,***882988**,49,NaN,***000000**,NaN
0,37517678191,IOAV BLANCHE,direta,***176781**,08029874000183,08029874,2,IOAV BLANCHE,***176781**,49,NaN,***000000**,NaN
0,47261897949,CARLOS VIAN,originaria,***618979**,08209182000117,08209182,2,CARLOS VIAN,***618979**,49,NaN,***000000**,NaN
0,37517678191,IOAV BLANCHE,direta,***176781**,08842831000112,08842831,2,IOAV BLANCHE,***176781**,5,NaN,***000000**,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,06451764949,CARLOS BENJAMIM MELO CORREA DA COSTA,direta,***517649**,02054530000148,02054530,2,CARLOS BENJAMIM MELO CORREA DA COSTA,***517649**,49,NaN,***000000**,NaN
0,40567222004,RICARDO LANG,originaria,***672220**,02648485000150,02648485,2,RICARDO LANG,***672220**,49,NaN,***000000**,NaN
0,17672538500,RAIMUNDO MAGALHAES COSTA,direta,***725385**,06852558000181,06852558,2,RAIMUNDO MAGALHAES COSTA,***725385**,16,NaN,***000000**,NaN
1,02582430820,JOAO CARLOS DI GENIO,direta,***824308**,02914675000171,02914675,2,JOAO CARLOS DI GENIO,***824308**,49,NaN,***000000**,NaN
0,13773623453,GENTIL FERREIRA DE SOUZA FILHO,direta,***736234**,08058802000164,08058802,2,GENTIL FERREIRA DE SOUZA FILHO,***736234**,10,NaN,***000000**,NaN

In [57]:
lista_cnpjs = df_socio1.drop_duplicates(['cnpj_basico'], keep='first')
lista_cnpjs.shape

(1435, 13)

In [58]:
lista_cnpjs = lista_cnpjs[['entidade_id', 'entidade_nome', 'cnpj', 'cnpj_basico', 'cpf_mascarado']]

In [59]:
lista_cnpjs

,entidade_id,entidade_nome,cnpj,cnpj_basico,cpf_mascarado
0,00279046871,SANDRO DA MABEL ANTONIO SCODRO,32329476000167,32329476,***790468**
0,92588298834,MARIO MAURICIO VASQUEZ BELTRAO,05296337000101,05296337,***882988**
0,37517678191,IOAV BLANCHE,08029874000183,08029874,***176781**
0,47261897949,CARLOS VIAN,08209182000117,08209182,***618979**
0,37517678191,IOAV BLANCHE,08842831000112,08842831,***176781**
...,...,...,...,...,...
0,06451764949,CARLOS BENJAMIM MELO CORREA DA COSTA,02054530000148,02054530,***517649**
0,40567222004,RICARDO LANG,02648485000150,02648485,***672220**
0,17672538500,RAIMUNDO MAGALHAES COSTA,06852558000181,06852558,***725385**
1,02582430820,JOAO CARLOS DI GENIO,02914675000171,02914675,***824308**
0,13773623453,GENTIL FERREIRA DE SOUZA FILHO,08058802000164,08058802,***736234**

In [60]:
empresas_encontradas = lista_cnpjs[(lista_cnpjs['cpf_mascarado'] == '***836606**') &
                              (lista_cnpjs['entidade_nome'] == 'RUBENS MENIN TEIXEIRA DE SOUZA')]
empresas_encontradas

Empty DataFrame
Columns: [entidade_id, entidade_nome, cnpj, cnpj_basico, cpf_mascarado]
Index: []

### Multas trabalhistas

In [61]:
kwargs = {'sep': ';', 'dtype': str, 'encoding': 'utf-8'}
autos_mte = pd.read_csv("originais/autos_mte_10anos.csv", **kwargs)

autos_mte = autos_mte[pd.notnull(autos_mte['cpf_cnpj_infrator'])]

def limpeza1(linha):
    documento = str(linha["cpf_cnpj_infrator"])
    documento = documento.strip()
    documento = documento.replace('.', '')
    documento = documento.replace('-', '')
    documento = documento.replace('/', '')
    return str(documento)
autos_mte["cpf_cnpj_infrator"] = autos_mte.apply(limpeza1, axis=1)

# Preenche zeros a esquerda nos documentos
def compara1(linha):
    documento = str(linha["cpf_cnpj_infrator"])
    
    if len(documento) < 14 and len(documento) >= 12:
        conta = 14 - (len(documento))
        zero = '0'
        zeros = zero * conta
        alterado = zeros + documento
    elif len(documento) == 14:
        alterado = documento
    elif len(documento) < 11:
        conta = 11 - (len(documento))
        zero = '0'
        zeros = zero * conta
        alterado = zeros + documento
    elif len(documento) == 11:
        alterado = documento
    
    return alterado
autos_mte["cpf_cnpj_infrator"] = autos_mte.apply(compara1, axis=1)

def limpeza2(linha):
    documento = str(linha["cpf_cnpj_infrator"])
    if len(documento) > 11:
        return documento[:8]
    else:
        return "documento_cpf"

autos_mte['cnpj_raiz'] = autos_mte.apply(limpeza2, axis=1)

In [62]:
autos_mte.columns

Index(['num_processo', 'cpf_cnpj_infrator', 'tipo_infracao', 'capitulacao',
       'valor_multa', 'data', 'reincidencia', 'cnpj_raiz'],
      dtype='object')

In [63]:
autos_mte

,num_processo,cpf_cnpj_infrator,tipo_infracao,capitulacao,valor_multa,data,reincidencia,cnpj_raiz
0,04623.600976/2019-29,01478313000112,FGTS,"Art. 23, §1º, inciso I, c/c art. 18, §1º, da L...","72,36",07/01/2020,N,01478313
1,04630.000684/2012-26,76483726001832,NR 05 - CIPA,"Artigo 157, Inciso I, da CLT, c/c item 5.50 da...","3030,29",19/04/2012,N,76483726
2,04646.600012/2014-16,07352882000101,Períodos de descanso,"Art. 71, 'caput' da CLT","3059,25",02/03/2016,N,07352882
3,04667.000284/2019-70,04084451000105,Registro de empregado,"Art. 41, 'caput', c/c art. 47, §1º, da Consoli...",3200,12/06/2019,N,04084451
4,04678.401163/2015-99,07102206000171,NR 18 - Condições e Meio Ambiente de Trabalho ...,"Artigo 157, Inciso I, da CLT, c/c item 18.2.1 ...","6708,08",18/01/2018,N,07102206
...,...,...,...,...,...,...,...,...
1048570,46254.003192/2017-81,09622736000176,Fiscalização,"Art. 630, § 4º da CLT","1368,61",03/04/2018,N,09622736
1048571,46254.003192/2019-43,27733974000130,FGTS,"Art. 23, §1º, inciso I, c/c art. 18, §1º, da L...","532,05",16/01/2020,N,27733974
1048572,46254.003193/2012-11,12542573000126,NR 01 - Disposições gerais,"art. 157, inciso I, da CLT, c/c item 1.7, alín...","2035,86",24/09/2013,N,12542573
1048573,46254.003193/2014-83,00831373003804,Jornada de trabalho,Art. 58 da CLT,"4025,33",30/10/2014,N,00831373
1048574,46254.003193/2015-64,08893267000167,Contrato individual de trabalho,Art. 444 da CLT,"402,53",21/08/2015,N,08893267

In [64]:
empresas_mte = pd.merge(lista_cnpjs, autos_mte.drop_duplicates('cnpj_raiz'), left_on='cnpj_basico', right_on='cnpj_raiz', how = 'left')

In [65]:
conta = empresas_mte[pd.notnull(empresas_mte['cpf_cnpj_infrator'])].copy()
conta.shape

(76, 13)

In [66]:
conta.head()

,entidade_id,entidade_nome,cnpj,cnpj_basico,cpf_mascarado,num_processo,cpf_cnpj_infrator,tipo_infracao,capitulacao,valor_multa,data,reincidencia,cnpj_raiz
11,31215203691,WALTER SANTANA ARANTES,09599852000111,09599852,***152036**,46246.001603/2012-99,09599852000111,FGTS,"Art. 23, § 1º, I da Lei nº 8.036/90","268,15",08/10/2012,N,09599852
103,62594370215,HELDER ZAHLUTH BARBALHO,04885828000125,04885828,***943702**,46222.002738/2015-92,04885828000125,FGTS,"Art. 23, § 1º, inciso I, da Lei nº 8.036, de 1...","587,38",31/01/2017,N,04885828
110,26695806888,ARIEL HOROVITZ,11902798000183,11902798,***958068**,46224.000911/2015-06,11902798000183,Fiscalização,"Art. 630, § 4º da CLT","2012,66",17/04/2015,N,11902798
115,03577163887,JOSE RIBEIRO DE MENDONCA,33277096000199,33277096,***771638**,46208.000132/2015-09,33277096000199,Rescisão do contrato de trabalho,"Art. 477, § 6º, al. 'b' da CLT","84278,7",10/12/2015,N,33277096
127,02582430820,JOAO CARLOS DI GENIO,43144138000177,43144138,***824308**,46219.003199/2012-15,43144138000177,Fiscalização,"Art. 630, § 4º da CLT","2012,66",29/07/2012,N,43144138

In [67]:
baixa = conta[['entidade_id', 'entidade_nome', 'cnpj', 'cnpj_basico', 'cpf_mascarado']]

In [68]:
TextFileReader = pd.read_csv('D://Code//nova_receita//empresas_fev_2022.csv',\
                             chunksize=1000,\
                             sep=',',\
                             converters={'cnpj_basico': lambda x: str(x)},\
                             usecols=['cnpj_basico', 
                                      'razao_social'])

In [69]:
now = datetime.now()
print("A extração começou às: ", now)

conta = 0
for df in TextFileReader:

    empresas_encontradas = pd.merge(baixa, \
                                 df, \
                                 left_on= 'cnpj_basico', \
                                 right_on='cnpj_basico')
    
    if empresas_encontradas.empty is False:
        if conta == 0:
            df_empresas1 = empresas_encontradas.copy()
        else:
             df_empresas1 = pd.concat([df_empresas1, empresas_encontradas])             
    
        conta = conta + 1
        
now = datetime.now()
print("A extração terminou às: ", now)

A extração começou às:  2022-08-09 09:38:45.412816
A extração terminou às:  2022-08-09 09:42:43.249768

In [70]:
df_empresas1.sample(5)

,entidade_id,entidade_nome,cnpj,cnpj_basico,cpf_mascarado,razao_social
0,02582430820,JOAO CARLOS DI GENIO,11918109000129,11918109,***824308**,AESA ENSINO SUPERIOR DE ALAGOAS LTDA.
0,13205285115,MAGDA MOFATTO HON,02167740000142,02167740,***052851**,THERMAS DI ROMA HOTEL CLUBE
0,02582430820,JOAO CARLOS DI GENIO,31300858000103,31300858,***824308**,AVIES ENSINO SUPERIOR DE VITORIA LTDA.
0,01754580904,ANTONIO CELSO SGANZERLA,83297515000122,83297515,***545809**,CELTE NAVEGACAO LTDA
0,28638042000,NESTOR MULLER,87246179000140,87246179,***380420**,ABASTECEDORA DE COMBUSTIVEIS E DERIVADOS PINGU...

In [80]:
df_empresas1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76 entries, 0 to 0
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   entidade_id    76 non-null     object
 1   entidade_nome  76 non-null     object
 2   cnpj           76 non-null     object
 3   cpf_mascarado  76 non-null     object
 4   cnpj_nome      76 non-null     object
dtypes: object(5)
memory usage: 3.6+ KB

In [72]:
df_empresas1.rename(columns = {'razao_social':'cnpj_nome'},inplace = True)
df_empresas1.drop('cnpj_basico', axis=1, inplace=True)

In [96]:
df_empresas1.to_csv('resultados/autos_mte/empresas_de_doadores_com_autos_trabalhistas_8ago.csv',index=False)

In [97]:
df_empresas1.to_excel('resultados/autos_mte/empresas_de_doadores_com_autos_trabalhistas_8ago.xlsx',sheet_name='Sheet1',index=False)

In [82]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
politicos = pd.read_csv("resultados/politicos_2018_versao_26jul_2022.csv", **kwargs)

In [83]:
politicos.columns

Index(['nome', 'foto', 'nome_urna', 'uf_eleicao_disputa', 'politico_id', 'uri',
       'sequencial_candidato', 'bancada_ruralista', 'id_interno',
       'doacao_ambiental_direta_total', 'doacao_ambiental_indireta_total',
       'doacao_ambiental_originaria_total', 'doacao_trabalhista_direta_total',
       'total_geral_doacoes_diretas', 'total_geral_doacoes_indiretas',
       'total_geral_doacoes_originarias', 'temperatura_ruralometro_2018',
       'partido_atual'],
      dtype='object')

In [86]:
procura_politicos = pd.merge(df_empresas1, politicos, left_on='entidade_id', right_on='politico_id')

In [87]:
procura_politicos

,entidade_id,entidade_nome,cnpj,cpf_mascarado,cnpj_nome,nome,foto,nome_urna,uf_eleicao_disputa,politico_id,...,id_interno,doacao_ambiental_direta_total,doacao_ambiental_indireta_total,doacao_ambiental_originaria_total,doacao_trabalhista_direta_total,total_geral_doacoes_diretas,total_geral_doacoes_indiretas,total_geral_doacoes_originarias,temperatura_ruralometro_2018,partido_atual
0,01960970453,LUIZ GONZAGA PATRIOTA,00044180000103,***609704**,CLUBE DO CONGRESSO,LUIZ GONZAGA PATRIOTA,https://www.camara.leg.br/internet/deputado/ba...,Gonzaga Patriota,PE,01960970453,...,74419,138600.0,NaN,NaN,NaN,1484245.2,NaN,NaN,37.1,PSB
1,13205285115,MAGDA MOFATTO HON,00071556000179,***052851**,ROMA HOTEIS E REALIZACOES LTDA,MAGDA MOFATTO HON,https://www.camara.leg.br/internet/deputado/ba...,Magda Mofatto,GO,13205285115,...,166402,240293.48,NaN,NaN,NaN,2371063.48,NaN,NaN,39.9704545454545,PL
2,13205285115,MAGDA MOFATTO HON,01753713000199,***052851**,DI ROMA EMPREENDIMENTOS IMOBILIARIOS LTDA,MAGDA MOFATTO HON,https://www.camara.leg.br/internet/deputado/ba...,Magda Mofatto,GO,13205285115,...,166402,240293.48,NaN,NaN,NaN,2371063.48,NaN,NaN,39.9704545454545,PL
3,13205285115,MAGDA MOFATTO HON,02167740000142,***052851**,THERMAS DI ROMA HOTEL CLUBE,MAGDA MOFATTO HON,https://www.camara.leg.br/internet/deputado/ba...,Magda Mofatto,GO,13205285115,...,166402,240293.48,NaN,NaN,NaN,2371063.48,NaN,NaN,39.9704545454545,PL
4,13205285115,MAGDA MOFATTO HON,03465317000191,***052851**,ROMA EMPREENDIMENTOS E TURISMO LTDA,MAGDA MOFATTO HON,https://www.camara.leg.br/internet/deputado/ba...,Magda Mofatto,GO,13205285115,...,166402,240293.48,NaN,NaN,NaN,2371063.48,NaN,NaN,39.9704545454545,PL
5,13205285115,MAGDA MOFATTO HON,12947899000133,***052851**,JARDINS DI ROMA COMERCIAL LTDA,MAGDA MOFATTO HON,https://www.camara.leg.br/internet/deputado/ba...,Magda Mofatto,GO,13205285115,...,166402,240293.48,NaN,NaN,NaN,2371063.48,NaN,NaN,39.9704545454545,PL
6,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,03719327000106,***885663**,PORTO PESCA LTDA,MARCOS ROBERIO RIBEIRO MONTEIRO,https://www.camara.leg.br/internet/deputado/ba...,Robério Monteiro,CE,37788566349,...,204489,98200.0,NaN,NaN,NaN,181830.0,NaN,NaN,NaN,PDT

In [88]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
doacoes_2018 = pd.read_csv("resultados/doacoes/doacoes_geral_politicos_2018.csv", **kwargs)

doacoes_2018['VR_RECEITA'] = doacoes_2018['VR_RECEITA'].str.replace(',','.')
doacoes_2018['VR_RECEITA'] = doacoes_2018['VR_RECEITA'].astype('float64') 

def limpeza5(linha):
    documento = str(linha["NR_CPF_CNPJ_DOADOR"])
    if len(documento) > 11:
        return documento[:8]
    else:
        return documento

doacoes_2018['doador_raiz'] = doacoes_2018.apply(limpeza5, axis=1)

In [89]:
doacoes_2018.columns

Index(['DT_RECEITA', 'NR_CPF_CANDIDATO', 'SQ_CANDIDATO', 'NM_CANDIDATO',
       'DS_FONTE_RECEITA', 'DS_NATUREZA_RECEITA', 'NR_CPF_CNPJ_DOADOR',
       'NM_DOADOR_RFB', 'DS_ESFERA_PARTIDARIA_DOADOR', 'NM_PARTIDO_DOADOR',
       'SQ_CANDIDATO_DOADOR', 'DS_CARGO_CANDIDATO_DOADOR', 'SG_PARTIDO_DOADOR',
       'DS_RECEITA', 'VR_RECEITA', 'doador_raiz'],
      dtype='object')

In [90]:
doacoes_elesmesmos = doacoes_2018[(doacoes_2018['NR_CPF_CANDIDATO'] == '33096473234') |
                              (doacoes_2018['NR_CPF_CANDIDATO'] == '01960970453') | 
                                  (doacoes_2018['NR_CPF_CANDIDATO'] == '13205285115') | 
                                  (doacoes_2018['NR_CPF_CANDIDATO'] == '37788566349') 
                                 ]

In [91]:
doacoes_elesmesmos = doacoes_elesmesmos[(doacoes_elesmesmos['NR_CPF_CNPJ_DOADOR'] == '33096473234') |
                              (doacoes_elesmesmos['NR_CPF_CNPJ_DOADOR']  == '01960970453') | 
                                 (doacoes_elesmesmos['NR_CPF_CNPJ_DOADOR']  == '13205285115') | 
                                  (doacoes_elesmesmos['NR_CPF_CNPJ_DOADOR'] == '37788566349') 
                                 ]

In [92]:
doacoes_elesmesmos

,DT_RECEITA,NR_CPF_CANDIDATO,SQ_CANDIDATO,NM_CANDIDATO,DS_FONTE_RECEITA,DS_NATUREZA_RECEITA,NR_CPF_CNPJ_DOADOR,NM_DOADOR_RFB,DS_ESFERA_PARTIDARIA_DOADOR,NM_PARTIDO_DOADOR,SQ_CANDIDATO_DOADOR,DS_CARGO_CANDIDATO_DOADOR,SG_PARTIDO_DOADOR,DS_RECEITA,VR_RECEITA,doador_raiz
3462,20/09/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,30000.00,37788566349
3463,17/10/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,7000.00,37788566349
3464,01/11/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,21200.00,37788566349
3465,04/10/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,15000.00,37788566349
3466,09/10/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,15000.00,37788566349
3467,05/10/2018,37788566349,60000611947,MARCOS ROBERIO RIBEIRO MONTEIRO,Outros Recursos,Financeiro,37788566349,MARCOS ROBERIO RIBEIRO MONTEIRO,#NULO#,Partido Democrático Trabalhista,60000611947,Deputado Federal,PDT,#NULO#,10000.00,37788566349
5412,09/10/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Financeiro,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,#NULO#,200.00,13205285115
5413,22/08/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,I/VW AMAROK CD 4X4· 11/11· PLACA NEV-2437,3000.00,13205285115
5414,30/11/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Financeiro,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,#NULO#,11793.48,13205285115
5415,20/09/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,FIAT STRADA ADVENTURE PLACA PAH-0840,1600.00,13205285115
5416,26/09/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Financeiro,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,#NULO#,150000.00,13205285115
5417,22/08/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,CARRO DE SOM - FORD/ F-4000· 15/15· PLACA PQC-...,5000.00,13205285115
5418,22/08/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,I/MMC PAJERO GLS3.2 D· 07/08· PLACA FPF-1118,3000.00,13205285115
5419,19/09/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,HYUNDAI HR HDB PLACA PRR-9563,5000.00,13205285115
5420,19/09/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,TOYOTA HILUX PLACA OOF-5848,2500.00,13205285115
5421,20/09/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Estimável,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,CELTA 1.0 PLACA ONA-9897,1200.00,13205285115
5422,29/10/2018,13205285115,90000620374,MAGDA MOFATTO HON,Outros Recursos,Financeiro,13205285115,MAGDA MOFATTO HON,#NULO#,Partido da República,90000620374,Deputado Federal,PR,#NULO#,57000.00,13205285115
11138,16/08/2018,33096473234,140000606372,CRISTIANO DUTRA VALE,Outros Recursos,Estimável,33096473234,CRISTIANO DUTRA VALE,#NULO#,Partido da República,140000606372,Deputado Federal,PR,VEICULO TOYOTA HILUX 4X4 DIESEL ANO 2011/2012 ...,8000.00,33096473234
11927,01/11/2018,01960970453,170000610284,LUIZ GONZAGA PATRIOTA,Outros Recursos,Financeiro,01960970453,LUIZ GONZAGA PATRIOTA,#NULO#,Partido Socialista Brasileiro,170000610284,Deputado Federal,PSB,#NULO#,40600.00,01960970453
11928,01/11/2018,01960970453,170000610284,LUIZ GONZAGA PATRIOTA,Outros Recursos,Financeiro,01960970453,LUIZ GONZAGA PATRIOTA,#NULO#,Partido Socialista Brasileiro,170000610284,Deputado Federal,PSB,#NULO#,28000.00,01960970453
11930,26/10/2018,01960970453,170000610284,LUIZ GONZAGA PATRIOTA,Outros Recursos,Financeiro,01960970453,LUIZ GONZAGA PATRIOTA,#NULO#,Partido Socialista Brasileiro,170000610284,Deputado Federal,PSB,#NULO#,10000.00,01960970453
11931,31/10/2018,01960970453,170000610284,LUIZ GONZAGA PATRIOTA,Outros Recursos,Financeiro,01960970453,LUIZ GONZAGA PATRIOTA,#NULO#,Partido Socialista Brasileiro,170000610284,Deputado Federal,PSB,#NULO#,40000.00,01960970453
11932,30/10/2018,01960970453,170000610284,LUIZ GONZAGA PATRIOTA,Outros Recursos,Financeiro,01960970453,LUIZ GONZAGA PATRIOTA,#NULO#,Partido Socialista Brasileiro,170000610284,Deputado Federal,PSB,#NULO#,20000.00,01960970453

In [93]:
doacoes_elesmesmos.to_excel('resultados/doacoes/doacoes_proprios_politicos_multas_trabalhistas.xlsx',sheet_name='Sheet1',index=False)

In [103]:
doacoes_elesmesmos.shape

(23, 17)

In [94]:
doacoes_elesmesmos['doacoes_tipo'] = 'direta'

In [99]:
para_site = doacoes_elesmesmos[['VR_RECEITA', 'NR_CPF_CANDIDATO', 'NR_CPF_CNPJ_DOADOR', 'NM_DOADOR_RFB', 'doacoes_tipo', 'DS_FONTE_RECEITA', 'DT_RECEITA']].copy()

In [100]:
para_site.rename(columns = {'VR_RECEITA':'valor'},inplace = True)
para_site.rename(columns = {'NR_CPF_CANDIDATO':'politico_id'},inplace = True)
para_site.rename(columns = {'NR_CPF_CNPJ_DOADOR':'entidade_id'},inplace = True)
para_site.rename(columns = {'NM_DOADOR_RFB':'entidade_nome'},inplace = True)
para_site.rename(columns = {'DS_FONTE_RECEITA':'origem_do_dinheiro_no_tse'},inplace = True)
para_site.rename(columns = {'DT_RECEITA':'data'},inplace = True)

In [102]:
para_site.shape

(23, 7)

In [104]:
para_site.to_csv('resultados/doacoes/doacoes_proprios_politicos_multas_trabalhistas.csv',index=False)

In [105]:
para_site.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 3462 to 11932
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   valor                      23 non-null     float64
 1   politico_id                23 non-null     object
 2   entidade_id                23 non-null     object
 3   entidade_nome              23 non-null     object
 4   doacoes_tipo               23 non-null     object
 5   origem_do_dinheiro_no_tse  23 non-null     object
 6   data1                      23 non-null     object
dtypes: float64(1), object(6)
memory usage: 1.4+ KB

### Multas ambientais

In [ ]:
# Embargos no Ibama

In [62]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
embargos_ibama = pd.read_csv("resultados/embargos_ibama/lista_entidades_embargos_ibama.csv", **kwargs)
embargos_ibama.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68162 entries, 0 to 68161
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   municipio          68162 non-null  object
 1   tipo_infracao      62576 non-null  object
 2   data_fiscalizacao  68161 non-null  object
 3   entidade_id        68162 non-null  object
 4   entidade_nome      68162 non-null  object
 5   estado_id          68162 non-null  object
 6   tamanho_area       29827 non-null  object
dtypes: object(7)
memory usage: 3.6+ MB

In [63]:
embargos_ibama

,municipio,tipo_infracao,data_fiscalizacao,entidade_id,entidade_nome,estado_id,tamanho_area
0,Novo Repartimento,Ficam embarcadas todas as atividades na área d...,2019-11-21,27433203000128,As de Outros Indústria e Comércio de Produtos ...,PA,NaN
1,São Gonçalo do Amarante,FICA EMBARGADO A ATIVIDADE DE TRANSPORTE DE CA...,2019-11-25,09572788000185,SS & B CONSTRUTORA LTDA,CE,NaN
2,Paragominas,NaN,2019-11-20,03532877000111,SERRARIA LUCAS LTDA. - EPP,PA,NaN
3,Boa Vista,Ficam embargadas as atividades da empresa em r...,2019-12-06,10327875000156,MADEREIRA IPE COM. IMP. EXP. LTDA - EPP,RR,NaN
4,Boa Vista,Ficam embargadas as atividades da empresa Made...,2019-11-30,13660639000145,N. J. DE OLIVEIRA NETO EIRELLI - EPP,RR,NaN
...,...,...,...,...,...,...,...
68157,Sinop,NaN,2021-12-30,01397090000169,Agropecuaria e Industrial Pimadel Ltda,MT,NaN
68158,Jaguaré,NaN,2020-06-03,09652212709,Liliany Bazoni Martins,ES,NaN
68159,Cavalcante,NaN,2020-03-17,22641629100,Francisco Tadeu Silva Guimarães,GO,NaN
68160,São Miguel do Guaporé,Infração da Flora(Não Classificada-Móvel),2021-01-15,65637844291,Edson Souza do Nascimento,RO,134.173
68161,Alta Floresta,Infração de Administração Ambiental(Não Classi...,2021-03-22,10502535822,Cibele Sousa Pinto,MT,NaN

In [64]:
empresas_embargos = pd.merge(lista_cnpjs, embargos_ibama.drop_duplicates('entidade_id'), left_on='cnpj', right_on='entidade_id', how = 'left')

In [65]:
conta = empresas_embargos[pd.notnull(empresas_embargos['tipo_infracao'])].copy()
conta.shape

(7, 12)

conta.columns

In [74]:
conta

,entidade_id_x,entidade_nome_x,cnpj,cnpj_basico,cpf_mascarado,municipio,tipo_infracao,data_fiscalizacao,entidade_id_y,entidade_nome_y,estado_id,tamanho_area
399,01522833404,PAULO FERNANDO CAVALCANTI DE MORAIS,04094192000101,04094192,***228334**,Rubiataba,"Destruir, desmatar, danificar florestas ou qua...",2011-01-11,04094192000101,Agro-Rub-Agropecuaria Ltda,GO,0.4
403,01324071320,EVERARDO FERREIRA TELLES,06604714000195,06604714,***240713**,Itaiçaba,Infração da Flora(Não Classificada-Móvel),2017-03-16,06604714000195,Santelisa Industria de Embalagens S/A,CE,40743.87
546,13205285115,MAGDA MOFATTO HON,03465317000191,03465317,***052851**,Caldas Novas,"Destruir (danificar, desmatar) florestas ou de...",2005-11-23,03465317000191,Roma Empreendimentos e Turismo Ltda,GO,NaN
578,66296676891,FERNANDO DE CASTRO MARQUES,04636936000164,04636936,***966768**,Mineiros,Impedir ou dificultar a regeneração natural de...,2012-06-08,04636936000164,Agropecuaria Pedra Branca Ltda,GO,16.0
985,32982402300,ANA ANGELICA MOURA SAMPAIO,01619130000170,01619130,***824023**,Zé Doca,"Construir, reformar, ampliar, instalar ou faze...",2012-09-13,01619130000170,Serraria Sampaio Ltda,MA,NaN
1127,03577163887,JOSE RIBEIRO DE MENDONCA,00819940000107,00819940,***771638**,Maurilândia,Infração da Flora(Não Classificada-Móvel),2017-07-14,00819940000107,J.Mendonça Agropecuária S/A.,GO,0.22
1136,00045741840,FERNANDO ANTONIO FERREIRA,83382721000130,83382721,***457418**,Vigia,"Construir, reformar, ampliar, instalar ou faze...",2012-10-03,83382721000130,Ecomar Industria de Pesca S/A,PA,NaN

In [66]:
baixa = conta[['entidade_id_x', 'entidade_nome_x', 'cnpj', 'cpf_mascarado']].copy()

In [67]:
baixa.rename(columns = {'entidade_id_x':'entidade_id'},inplace = True)
baixa.rename(columns = {'entidade_nome_x':'entidade_nome'},inplace = True)

In [71]:
baixa['cnpj_basico']= baixa['cnpj'].str[:8]

In [74]:
baixa[['cnpj_basico', 'cnpj']]

     cnpj_basico            cnpj
399     04094192  04094192000101
403     06604714  06604714000195
546     03465317  03465317000191
578     04636936  04636936000164
985     01619130  01619130000170
1127    00819940  00819940000107
1136    83382721  83382721000130

In [75]:
baixa.columns

Index(['entidade_id', 'entidade_nome', 'cnpj', 'cpf_mascarado', 'cnpj_basico'], dtype='object')

In [76]:
TextFileReader = pd.read_csv('D://Code//nova_receita//empresas_fev_2022.csv',\
                             chunksize=1000,\
                             sep=',',\
                             converters={'cnpj_basico': lambda x: str(x)},\
                             usecols=['cnpj_basico', 
                                      'razao_social'])

In [77]:
now = datetime.now()
print("A extração começou às: ", now)

conta = 0
for df in TextFileReader:

    empresas_encontradas = pd.merge(baixa, \
                                 df, \
                                 left_on= 'cnpj_basico', \
                                 right_on='cnpj_basico')
    
    if empresas_encontradas.empty is False:
        if conta == 0:
            df_empresas1 = empresas_encontradas.copy()
        else:
             df_empresas1 = pd.concat([df_empresas1, empresas_encontradas])             
    
        conta = conta + 1
        
now = datetime.now()
print("A extração terminou às: ", now)

A extração começou às:  2022-06-17 11:34:51.745053
A extração terminou às:  2022-06-17 11:38:43.195627

In [78]:
df_empresas1.rename(columns = {'razao_social':'cnpj_nome'},inplace = True)
df_empresas1.drop('cnpj_basico', axis=1, inplace=True)

In [79]:
df_empresas1

,entidade_id,entidade_nome,cnpj,cpf_mascarado,cnpj_nome
0,00045741840,FERNANDO ANTONIO FERREIRA,83382721000130,***457418**,ECOMAR INDUSTRIA DE PESCA S/A EM RECUPERACAO J...
0,03577163887,JOSE RIBEIRO DE MENDONCA,00819940000107,***771638**,J. MENDONCA AGROPECUARIA S.A
0,32982402300,ANA ANGELICA MOURA SAMPAIO,01619130000170,***824023**,SERRARIA SAMPAIO LTDA
0,13205285115,MAGDA MOFATTO HON,03465317000191,***052851**,ROMA EMPREENDIMENTOS E TURISMO LTDA
0,01522833404,PAULO FERNANDO CAVALCANTI DE MORAIS,04094192000101,***228334**,AGRO-RUB AGROPECUARIA LTDA
0,66296676891,FERNANDO DE CASTRO MARQUES,04636936000164,***966768**,AGROPECUARIA PEDRA BRANCA LTDA
0,01324071320,EVERARDO FERREIRA TELLES,06604714000195,***240713**,SANTELISA INDUSTRIA DE EMBALAGENS S/A

In [80]:
df_empresas1.to_csv('resultados/embargos_ibama/empresas_de_doadores_com_embargos_no_ibama.csv',index=False)

In [ ]:
# Autos de infracao no Ibama

In [88]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
autos_ibama = pd.read_csv("resultados/autos_ibama/lista_entidades_autos_de_infracao_ibama.csv", **kwargs)
autos_ibama.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525101 entries, 0 to 525100
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   municipio          525096 non-null  object
 1   tipo_infracao      525101 non-null  object
 2   data_fiscalizacao  525096 non-null  object
 3   entidade_id        525101 non-null  object
 4   entidade_nome      525096 non-null  object
 5   estado_id          525096 non-null  object
 6   tamanho_area       32881 non-null   object
 7   valor              523165 non-null  object
dtypes: object(8)
memory usage: 32.0+ MB

In [89]:
autos_ibama.head()

,municipio,tipo_infracao,data_fiscalizacao,entidade_id,entidade_nome,estado_id,tamanho_area,valor
0,TRIUNFO,Penalidade pecuniária - Flora,14/05/1998 00:00:00,***065424**,IVALDO GOMES DE LIMA,PE,NaN,636
1,PESQUEIRA,Penalidade pecuniária - Flora,18/05/1998 00:00:00,***890454**,OSVALDO CAMILO DA SILVA,PE,NaN,300
2,TRAIRI,Penalidade pecuniária - Flora,16/12/1998 00:00:00,69366599000188,J . O REBOUÇAS,CE,NaN,200
3,CAIBATE,Penalidade pecuniária - Flora,10/07/1998 00:00:00,75528604000104,AGRICOLA INDUSTRIAL DO SUL LTDA,RS,NaN,200
4,CRUZ,Penalidade pecuniária - Flora,17/12/1998 00:00:00,00789473000110,I.M NASCIMENTO ME,CE,NaN,150

In [90]:
empresas_autos_ibama = pd.merge(lista_cnpjs, autos_ibama.drop_duplicates('entidade_id'), left_on='cnpj', right_on='entidade_id', how = 'left')

In [91]:
conta = empresas_autos_ibama[pd.notnull(empresas_autos_ibama['tipo_infracao'])].copy()
conta.shape

(50, 13)

In [92]:
conta.columns

Index(['entidade_id_x', 'entidade_nome_x', 'cnpj', 'cnpj_basico',
       'cpf_mascarado', 'municipio', 'tipo_infracao', 'data_fiscalizacao',
       'entidade_id_y', 'entidade_nome_y', 'estado_id', 'tamanho_area',
       'valor'],
      dtype='object')

In [93]:
baixa = conta[['entidade_id_x', 'entidade_nome_x', 'cnpj', 'cnpj_basico', 'cpf_mascarado']].copy()

In [94]:
baixa.rename(columns = {'entidade_id_x':'entidade_id'},inplace = True)
baixa.rename(columns = {'entidade_nome_x':'entidade_nome'},inplace = True)

In [95]:
TextFileReader = pd.read_csv('D://Code//nova_receita//empresas_fev_2022.csv',\
                             chunksize=1000,\
                             sep=',',\
                             converters={'cnpj_basico': lambda x: str(x)},\
                             usecols=['cnpj_basico', 
                                      'razao_social'])

In [96]:
now = datetime.now()
print("A extração começou às: ", now)

conta = 0
for df in TextFileReader:

    empresas_encontradas = pd.merge(baixa, \
                                 df, \
                                 left_on= 'cnpj_basico', \
                                 right_on='cnpj_basico')
    
    if empresas_encontradas.empty is False:
        if conta == 0:
            df_empresas1 = empresas_encontradas.copy()
        else:
             df_empresas1 = pd.concat([df_empresas1, empresas_encontradas])             
    
        conta = conta + 1
        
now = datetime.now()
print("A extração terminou às: ", now)

A extração começou às:  2022-06-17 11:41:22.841210
A extração terminou às:  2022-06-17 11:45:21.141063

In [97]:
df_empresas1.rename(columns = {'razao_social':'cnpj_nome'},inplace = True)
df_empresas1.drop('cnpj_basico', axis=1, inplace=True)

In [99]:
df_empresas1.head()

,entidade_id,entidade_nome,cnpj,cpf_mascarado,cnpj_nome
0,38380196953,JAIME MAXIMINO BAGATTOLI,63745228000120,***801969**,TRANSPORTADORA GIOMILA LTDA
0,42931550663,ADAO RIBEIRO SOARES,64481450000126,***315506**,TRANSPORTE RIBEIRO E SOARES LTDA
0,39727254934,WALTER SCHLATTER,70355771000187,***272549**,AGRO BOLSAO ARMAZENS GERAIS COMERCIO DE CEREAI...
0,00585831904,ASSIS GURGACZ,76080738000178,***858319**,EUCATUR-EMPRESA UNIAO CASCAVEL DE TRANSPORTES ...
0,52141489849,LINCOLN LAFAIETE DA SILVEIRA BUENO,83318790000185,***414898**,MAFRIPAR BRANDS MANAGEMENT LTDA

In [100]:
df_empresas1.to_csv('resultados/autos_ibama/empresas_de_doadores_com_autos_no_ibama.csv',index=False)

In [86]:
# Autos ICMBIO

In [112]:
kwargs = {'sep': ',', 'dtype': str, 'encoding': 'utf-8'}
autos_icmbio = pd.read_csv("resultados/autos_icmbio/lista_entidades_autos_icmbio.csv", **kwargs)
autos_icmbio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1882 entries, 0 to 1881
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   municipio          1882 non-null   object
 1   tipo_infracao      1855 non-null   object
 2   data_fiscalizacao  1882 non-null   object
 3   entidade_id        1882 non-null   object
 4   entidade_nome      1882 non-null   object
 5   estado_id          1882 non-null   object
 6   valor_multa        1862 non-null   object
dtypes: object(7)
memory usage: 103.0+ KB

In [113]:
autos_icmbio.head()

,municipio,tipo_infracao,data_fiscalizacao,entidade_id,entidade_nome,estado_id,valor_multa
0,Palmeiras,NaN,2020-10-13,30989388115,Luiz Oscar Marques Ferreira,BA,500
1,Jijoca de Jericoacoara,"realizar serviÃ§o comercial "" passeio de quadr...",2021-02-25,31753302000164,Francisco Alcenir Rodrigues de Souza,CE,1000
2,Parati,NaN,2019-10-01,22327400000149,CIDADE JARDIM COMERCIO DE MADEIRAS LTDA,RJ,500
3,Porto Velho,"Destruir 58,7062 hectares de floresta nativa, ...",2020-04-07,15813798897,Luiz Felipe Grava do Val Nascimento,RO,590000
4,Parati,Causar dano a Ãrea de ProteÃ§Ã£o Ambiental de...,2021-03-05,04701852872,Vilson Predolim,RJ,10200

In [114]:
empresas_autos_icmbio = pd.merge(lista_cnpjs, autos_icmbio.drop_duplicates('entidade_id'), left_on='cnpj', right_on='entidade_id', how = 'left')

In [115]:
conta = empresas_autos_ibama[pd.notnull(empresas_autos_ibama['tipo_infracao'])].copy()
conta.shape

(50, 13)

In [116]:
conta.columns

Index(['entidade_id_x', 'entidade_nome_x', 'cnpj', 'cnpj_basico',
       'cpf_mascarado', 'municipio', 'tipo_infracao', 'data_fiscalizacao',
       'entidade_id_y', 'entidade_nome_y', 'estado_id', 'tamanho_area',
       'valor'],
      dtype='object')

In [117]:
baixa = conta[['entidade_id_x', 'entidade_nome_x', 'cnpj', 'cnpj_basico', 'cpf_mascarado']].copy()

In [118]:
baixa.rename(columns = {'entidade_id_x':'entidade_id'},inplace = True)
baixa.rename(columns = {'entidade_nome_x':'entidade_nome'},inplace = True)

In [119]:
TextFileReader = pd.read_csv('D://Code//nova_receita//empresas_fev_2022.csv',\
                             chunksize=1000,\
                             sep=',',\
                             converters={'cnpj_basico': lambda x: str(x)},\
                             usecols=['cnpj_basico', 
                                      'razao_social'])

In [120]:
now = datetime.now()
print("A extração começou às: ", now)

conta = 0
for df in TextFileReader:

    empresas_encontradas = pd.merge(baixa, \
                                 df, \
                                 left_on= 'cnpj_basico', \
                                 right_on='cnpj_basico')
    
    if empresas_encontradas.empty is False:
        if conta == 0:
            df_empresas1 = empresas_encontradas.copy()
        else:
             df_empresas1 = pd.concat([df_empresas1, empresas_encontradas])             
    
        conta = conta + 1
        
now = datetime.now()
print("A extração terminou às: ", now)

A extração começou às:  2022-06-17 11:52:33.664074
A extração terminou às:  2022-06-17 11:56:29.619397

In [121]:
df_empresas1.rename(columns = {'razao_social':'cnpj_nome'},inplace = True)
df_empresas1.drop('cnpj_basico', axis=1, inplace=True)

In [122]:
df_empresas1.head()

,entidade_id,entidade_nome,cnpj,cpf_mascarado,cnpj_nome
0,38380196953,JAIME MAXIMINO BAGATTOLI,63745228000120,***801969**,TRANSPORTADORA GIOMILA LTDA
0,42931550663,ADAO RIBEIRO SOARES,64481450000126,***315506**,TRANSPORTE RIBEIRO E SOARES LTDA
0,39727254934,WALTER SCHLATTER,70355771000187,***272549**,AGRO BOLSAO ARMAZENS GERAIS COMERCIO DE CEREAI...
0,00585831904,ASSIS GURGACZ,76080738000178,***858319**,EUCATUR-EMPRESA UNIAO CASCAVEL DE TRANSPORTES ...
0,52141489849,LINCOLN LAFAIETE DA SILVEIRA BUENO,83318790000185,***414898**,MAFRIPAR BRANDS MANAGEMENT LTDA

In [123]:
df_empresas1.to_csv('resultados/autos_icmbio/empresas_de_doadores_com_autos_no_icmbio.csv',index=False)